config/routes.rb
Rails.application.routes.draw do
  root 'manufacturers#index'

  resources :manufacturers, only: [:index, :new, :create]
  resources :cars, only: [:index, :new, :create]
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :manufacturer, presence: true
  validates :color, presence: true
  validates :year, presence: true
  validates :year, numericality: {only_integer: true, greater_than_or_equal_to: 1920}
  validates :mileage, presence: true
  validates :mileage, numericality: {only_integer: true}
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars

  validates :name, presence: true
  validates :country, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      flash[:success] = "Car added successfully"
      redirect_to cars_path
    else
      flash[:warning] = @car.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def car_params
    params.require(:car).permit(:manufacturer_id, :color, :year, :mileage)
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if @manufacturer.save
      flash[:success] = "Manufacturer added successfully"
      redirect_to manufacturers_path
    else
      flash[:warning] = @manufacturer.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h2>List of Cars</h2>

<ul>
  <% @cars.each do |car| %>
    <li><%=car.manufacturer.name%></li>
    <ul>
      <li><%=car.color%></li>
      <li><%=car.year%></li>
      <li><%=car.mileage%></li>
    </ul>
  <% end %>
</ul>


<%= link_to "Add New Car", new_car_path%>
<br>
<%= link_to "View Manufacturers List", manufacturers_path%>

app/views/cars/new.html.erb
<h1>Add a New Car:</h1>

<%= form_for @car do |f| %>
  <%= f.label :manufacturer_id %>
  <%= f.collection_select :manufacturer_id, Manufacturer.all, :id, :name %>
    </br>
  <%= f.label :color, "Color" %>
  <%= f.text_field :color %>
    </br>
  <%= f.label :year, "Year" %>
  <%= f.number_field :year, min: 1920 %>
    </br>
  <%= f.label :mileage, "Mileage" %>
  <%= f.number_field :mileage %>
    </br>
  <%= f.submit "Create Car" %>
<% end %>

<%= link_to 'Return to Cars', cars_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListings</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |key, val|%>
    <div class="flash flash-<%=key%>">
      <%= val %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/manufacturers/index.html.erb
<h2>List of Manufacturers</h2>

<ul>
  <% @manufacturers.each do |manufacturer| %>
  <li>Name: <%=manufacturer.name%> (Country: <%=manufacturer.country%>)</li>
  <% end %>
</ul>


<%= link_to "Add New Manufacturer", new_manufacturer_path%>
<br>
<%= link_to "Add New Car", new_car_path%>
<br>
<%= link_to "View Cars List", cars_path%>

app/views/manufacturers/new.html.erb
<h1>Add a New Manufacturer:</h1>

<%= form_for @manufacturer do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
    </br>
  <%= f.label :country, "Country" %>
  <%= f.text_field :country %>
    </br>
  <%= f.submit "Create Manufacturer" %>
<% end %>

<%= link_to 'Return to Manufacturers', manufacturers_path%>